replicaCount: 1

image:
  repository: 696938875922.dkr.ecr.ap-northeast-2.amazonaws.com/apps/etf-canvas-api
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 4000
  targetPort: 4000

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

env: []

seedCronJob:
  enabled: true
  schedule: "0 16 * * 1-5"
  discordWebhook: "https://discord.com/api/webhooks/1479675781142806528/RgcDhBAfN9gGe_Ya2UQqLSOjnmYfD7RcRPeiBakScossOzIFYy0W8gVVO1SC7Uvwu0jN"

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

nodeSelector: {}
tolerations: []
